"""empty message

Revision ID: 8d4ebf1e3ad9
Revises: 43a2583bb1c1
Create Date: 2022-11-14 23:27:25.009620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d4ebf1e3ad9'
down_revision = '43a2583bb1c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('author_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'author_name')
    # ### end Alembic commands ###
