"""empty message

Revision ID: e48b05ce1cfc
Revises: 8d4ebf1e3ad9
Create Date: 2022-11-15 13:26:04.574586

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e48b05ce1cfc'
down_revision = '8d4ebf1e3ad9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('answer_ibfk_1', 'answer', type_='foreignkey')
    op.drop_constraint('answer_ibfk_2', 'answer', type_='foreignkey')
    op.create_foreign_key(None, 'answer', 'question', ['question_id'], ['id'])
    op.create_foreign_key(None, 'answer', 'user', ['author_id'], ['id'])
    op.alter_column('question', 'content',
               existing_type=mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               nullable=False)
    op.drop_constraint('question_ibfk_1', 'question', type_='foreignkey')
    op.create_foreign_key(None, 'question', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.create_foreign_key('question_ibfk_1', 'question', 'user', ['author_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.alter_column('question', 'content',
               existing_type=mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               nullable=True)
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.create_foreign_key('answer_ibfk_2', 'answer', 'question', ['question_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key('answer_ibfk_1', 'answer', 'user', ['author_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    # ### end Alembic commands ###
